-- MySQL Script generated by MySQL Workbench
-- Sun Jul 15 00:28:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema walldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema walldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `walldb` DEFAULT CHARACTER SET utf8 ;
USE `walldb` ;

-- -----------------------------------------------------
-- Table `walldb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walldb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first` VARCHAR(25) NULL,
  `last` VARCHAR(25) NULL,
  `email` VARCHAR(25) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walldb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walldb`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `CreatorId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_users_idx` (`CreatorId` ASC),
  CONSTRAINT `fk_messages_users`
    FOREIGN KEY (`CreatorId`)
    REFERENCES `walldb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `walldb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `walldb`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `CreatorId` INT NOT NULL,
  `MessageId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`CreatorId` ASC),
  INDEX `fk_comments_messages1_idx` (`MessageId` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`CreatorId`)
    REFERENCES `walldb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_messages1`
    FOREIGN KEY (`MessageId`)
    REFERENCES `walldb`.`messages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
